[package]
name = "outlook-pst-rw"
description = "Read, create, and incrementally append Unicode Outlook PST archives"
version = "1.2.2"

authors = ["Microsoft", "dongs0104"]
edition.workspace = true
rust-version.workspace = true
repository = "https://github.com/dongs0104/outlook-pst-rs"
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "outlook_pst"

[dependencies]
byteorder.workspace = true
thiserror.workspace = true
tracing.workspace = true

[[example]]
name = "gen-fixture-pst"
path = "examples/gen-fixture-pst.rs"

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
codepage-strings.workspace = true
compressed-rtf.workspace = true
crossterm.workspace = true
ratatui.workspace = true
tracing-subscriber = { workspace = true, features = [ "env-filter" ] }
